### ISSUE TITLE
Compilation failure with C++17 standard

### ISSUE THREAD

**Issue by amadio** [italiangrid/voms#114]
The `struct data` in `voms/voms_api.h` clashes with `std::data` from C++17, and causes the compilation error below:
```
/usr/include/voms/voms_api.h:115:19: error: template argument 1 is invalid
  115 |   std::vector<data> std;   /*!< User's characteristics */
      |                   ^
/usr/include/voms/voms_api.h:115:19: error: template argument 2 is invalid
```
This bug has been found after trying to compile XRootD with support for voms with C++17 standard. The build error can be seen [here](https://github.com/xrootd/xrootd/actions/runs/4243982694/jobs/7377461322#step:5:569).

A potential fix is to use `std::vector<::data>` to disambiguate, but it's also probable that `std` as the variable name will have to be changed as well to avoid further name clashes with the standard C++ namespace `std::`.

**Comment by amadio** [comment]
I think you are right, I searched a bit further and found a `using namespace std;` in `XrdOucString.hh` which may be the cause of the clash, as it may be indirectly included in that source file. I will try to fix this on our end first, but it's probably not a bad idea to qualify `data` as `::data` in voms headers anyway.

**Comment by giacomini** [comment]
I thought a bit more about it and indeed it would be good to qualify `data` in the VOMS codebase, otherwise it would break if a previously-included header file does `using namespace std;`.
Thanks for catching this.

**Comment by amadio** [comment]
Closing, as there's no bug to actually be fixed in VOMS. Thank you!
