### ISSUE TITLE
`voms_api.h` expects `config.h`, which is not installed automatically

### ISSUE THREAD

**Issue by ShamrockLee** [italiangrid/voms#123]
Since 5c022c1d5fecd1a844b55f11acd4b410170acdd3, the VOMS C++ API header [`voms_api.h`](https://github.com/italiangrid/voms/blob/5c022c1d5fecd1a844b55f11acd4b410170acdd3/src/api/ccapi/voms_api.h#L29) contains

```
#include "config.h"
```

but such file is not installed into the destination include path, causing compilation failure for programs that uses this API header.

**Comment by giacomini** [comment]
That commit was reverted by https://github.com/italiangrid/voms/commit/25dfdfc41b9dafdbe3b140d7b9f4ef61c7cd57ac and a better fix was committed soon after https://github.com/italiangrid/voms/commit/b7a926e38db6b883f012c39ebcb10b4ee20912cc. However they are not incorporated yet in a (pre)release, but you can get directly the develop branch in the meantime. If that is not satisfactory for you, I'll see if I can prepare a (pre)release soon.
