### ISSUE TITLE
Adapt client libraries and clients to VOMS-AA

### ISSUE THREAD

**Issue by giacomini** [italiangrid/voms#124]
VOMS-AA is the VOMS endpoint of [INDIGO-IAM](https://github.com/indigo-iam/iam)

**Comment by bbockelm** [comment]
@giacomini - what's the current plans / timelines on this?  Particularly, is a new client going to be available prior to the shutdown of the WLCG VOMS-Admin instances?

**Comment by giacomini** [comment]
Yes. I've opened a PR with the current work, which I'd like to merge next week. Feel free to review.

**Comment by giacomini** [comment]
The option `-order` doesn't work for `voms-proxy-init`. This is because the request to the server is something like `GET /generate-ac?fqans=/test.vo&lifetime=43200&order=/test.vo/G1`, but VOMS-AA uses only the `fqans` list. In fact, the java version sends `GET /generate-ac?fqans=/test.vo/G1&lifetime=43200`, which apparently is processed correctly also by the VOMS server.
