### ISSUE TITLE
Make sysconfig environment optional in systemd unit?

### ISSUE THREAD

**Issue by sfayer** [italiangrid/voms#132]
Hi,

Would it be possible to make the /etc/sysconfig/voms file optional in the unit file by prefixing it by "-"? This file isn't included in the voms-server package in EPEL, so vomsd won't start without creating it.

Regards,
Simon

**Comment by giacomini** [comment]
It makes sense. Thanks.

**Comment by giacomini** [comment]
Fixed in 19a84d8
