### ISSUE TITLE
Can not load the PEM private key

### ISSUE THREAD

**Issue by talamoig** [italiangrid/voms#14]
Hello,

on a SL 5.8 I have the following error, when launching voms-proxy-init:
Enter GRID pass phrase for this identity:
Credentials couldn't be loaded [/root/.globus/userkey.pem, /root/.globus/usercert.pem]: Can not load the PEM private key: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
No credentials found!

The file have the correct permissions/ownership:
-rw-r--r-- 1 root root 3481 Sep  8 11:05 usercert.pem
-r-------- 1 root root 1900 Sep  8 11:06 userkey.pem

With the --debug option I get:
Enter GRID pass phrase for this identity:
Credentials couldn't be loaded [/root/.globus/userkey.pem, /root/.globus/usercert.pem]: Can not load the PEM private key: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
Looking for user credentials in [/root/.globus/usercred.p12]...
Credentials couldn't be loaded [/root/.globus/usercred.p12]: /root/.globus/usercred.p12 (cannot read file)
No credentials found!
org.italiangrid.voms.VOMSError: No credentials found!
        at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.initProxy(DefaultVOMSProxyInitBehaviour.java:160)
        at org.italiangrid.voms.clients.VomsProxyInit.execute(VomsProxyInit.java:263)
        at org.italiangrid.voms.clients.VomsProxyInit.<init>(VomsProxyInit.java:55)
        at org.italiangrid.voms.clients.VomsProxyInit.main(VomsProxyInit.java:40)

Using them on another machine is working fine.

I'm using voms-clients3-3.0.4-1.sl5, jdk-1.7.0_45-fcs and bouncycastle146-mail-1.46-2.

Best,
Ivano

**Comment by andreypz** [comment]
I'm seeing the same problem on SLC6.
Do you have a solution?

**Comment by andreaceccanti** [comment]
very likely is misconfiguration on your side, or wrong password. I cannot really tell without further information.

**Comment by andreypz** [comment]
For other people who may come here from google:
in our case the problem was due to old version of java. Updating java solved the issue.
