### ISSUE TITLE
"make check" fails if "make install" has not already been run

### ISSUE THREAD

**Issue by ryandesign** [italiangrid/voms#4]
With voms 2.0.9, running `make check` fails with this message:

```
Doing Initialization......................../tmp/suitefiles-FGUj6b/vomsinit.sh: line 2: /opt/local/share/voms/voms_install_db: No such file or directory
```

The message is correct: no such file or directory exists, because I have not yet run `make install`; I have only run `./configure` and `make` and `make check`. It is surprising to be expected to have run `make install` before running `make test`; usually one runs `make check`, and after confirming that the tests pass, then one runs `make install`.

It would be even more surprising if I actually did have voms installed, and then ran `make check` in the course of trying to build a different version, because the test would then be testing part of the old installation and part of the new build, which might lead to false positives or false negatives.

**Comment by giacomini** [comment]
The unit tests suite is not maitained any more. Tests are base on an external [testsuite](https://github.com/italiangrid/voms-testsuite).
