### ISSUE TITLE
Missing return statement in ERR_load_proxy_error_strings()

### ISSUE THREAD

**Issue by msalle** [italiangrid/voms#48]
Hi,
the new function `ERR_load_proxy_error_strings()` in https://github.com/italiangrid/voms/blame/master/src/sslutils/sslutils.c#L411-L423 is declared to return a `int` but does not. That would result in popping random data from the stack if you would be using the return value. Since it is (currently) never used in the code, I would probably declare it as returning `void`.

**Comment by andreaceccanti** [comment]
Hi Mischa, 
this will be fixed in the next release, thanks for pointing this out.

**Comment by msalle** [comment]
Great!
And thanks to openSUSE's build service which found it for me (-;
