### ISSUE TITLE
Outdate reference to EMI3 repository in VOMS Clients guide

### ISSUE THREAD

**Issue by Feandil** [italiangrid/voms#76]
The latest documentation for VOMS clients (https://github.com/italiangrid/voms/blob/gh-pages/documentation/voms-clients-guide/3.0.4/index.md) still says:
```
To install the VOMS clients, configure the EMI 3 repositories as appropriate
for the distribution where you will install the VOMS clients.

On Scientific Linux 5 or 6, voms clients are installed with the following command:
```

The EMI 3 repositories have been retired two to three years ago, initially replaced by UMD (and now even by EPEL? I see https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-411e6dcede)

Maybe the pointers should be updated (also maybe pointing to SL/Centos 7 ;) )

**Comment by andreaceccanti** [comment]
Hi Vincent,

thanks!
This is now fixed:

http://italiangrid.github.io/voms/documentation/voms-clients-guide/3.0.3/#install







Il giorno mer 29 gen 2020 alle ore 21:44 Vincent Brillault <
notifications@github.com> ha scritto:
