### ISSUE TITLE
voms-proxy-init stuck on OBJ_create

### ISSUE THREAD

**Issue by andrzejnovak** [italiangrid/voms#81]
I've have voms installed in conda. Running`voms-proxy-init` get stuck form some reason on `OBJ_create`. Strange thing is that terminating it, there is still a valid proxy created.
```
Enter GRID pass phrase:
Your identity: /C=DE/O=GermanGrid/OU=RWTH/CN=Andrzej Novak
oid exists
Function: OBJ_create
```

**Comment by giacomini** [comment]
If this issue is still valid, which platform are you using? which voms version?

**Comment by dvandok** [comment]
I'm now seeing more or less the same but without the `oid exists` and further. A strace shows that the program (voms-proxy-init Version: 2.1.1 Compiled: Oct 26 2022 07:40:44) is stuck in a loop opening `/cvmfs/dirac.egi.eu/dirac/8.0.3/diracos/etc` and never closing it, so it runs out of file descriptors.

**Comment by dvandok** [comment]
problem actually seems to be due to the program being unable to find the correct vomses file for the requested VO.
If I pass the explicit `--vomses=/etc/vomses/km3net.org-voms02.scope.unina.it ` option, it works.
