### ISSUE TITLE
New unit file fails for VOs containing - in the name (or similar)

### ISSUE THREAD

**Issue by msalle** [italiangrid/voms#83]
Problem: The new unit file https://github.com/italiangrid/voms/blob/2.0.15-systemd/systemd/voms%40.service fails for VOs containing e.g. `-` in their name (such as `rcdemo.aarc-project.eu.service`).

Details: The `ExecStart` line is using an uppercase `%I` which does 'unescaping', meaning a '-' becomes a '/', see https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers and explanation in https://unix.stackexchange.com/a/552784
Hence voms tries to start using
```/usr/sbin/voms --conf /etc/voms/rcdemo.aarc/project.eu/voms.conf```
instead of
```/usr/sbin/voms --conf /etc/voms/rcdemo.aarc-project.eu/voms.conf```

Solution: replace
`ExecStart=/usr/sbin/voms --conf /etc/voms/%I/voms.conf`
with
`ExecStart=/usr/sbin/voms --conf /etc/voms/%i/voms.conf`

**Comment by andreaceccanti** [comment]
Fixed with voms 2.0.16
