### ISSUE TITLE
New unit file needs a requirement on the database connector

### ISSUE THREAD

**Issue by msalle** [italiangrid/voms#84]
The `[Unit]` block in the new unit file https://github.com/italiangrid/voms/blob/2.0.15-systemd/systemd/voms%40.service needs an `After=<database>.service` where database is the used database implementation such as mariadb. Without this, the VOMS server doesn't boot correctly since voms starts much faster than e.g. mariadb.
Since it is dependent on the type of connector, it is probably best to add a drop in file (see https://www.freedesktop.org/software/systemd/man/systemd.unit.html) in /etc/systemd/system/voms@.service.d/, e.g. `/etc/systemd/system/voms@.service.d/after-mariadb.conf` containing
```
[Unit]
After=mariadb.service
```
which could then be added to the voms-mysql-plugin rpm.

**Comment by marcelovilaca** [comment]
https://github.com/italiangrid/voms-mysql-plugin/pull/2

https://github.com/italiangrid/pkg.voms/pull/2
