### ISSUE TITLE
SEGV when extension cannot be decoded

### ISSUE THREAD

**Issue by abh3** [italiangrid/voms#87]
In api_util.cc (VOSM 2.0.15 C++) we have these two statements (line numbers shown):

    611       AC_CERTS *certs = (AC_CERTS *)X509V3_EXT_d2i(ext);
    612       STACK_OF(X509) *certstack = certs->stackcert;

The issue is that if X509V3_EXT_d2i() cannot decode the given extension (which is possible for any number of reasonable reasons) it returns a nil pointer. That causes the assignment on line 612 to trigger a SEGV. I suggest that all uses of this function (there are several) check if the result is a nil pointer.

**Comment by andreaceccanti** [comment]
We will implement stronger sanity checks on the VOMS AC extension.
This said, the VOMS server implementations we maintain always include the AC_CERTS extension in the VOMS AC AFAIR. I guess you get the extension that causes you trouble from a non-compliant VOMS server, which should be fixed.

**Comment by giacomini** [comment]
I've committed a minimal fix. Please have a look.
@abh3, I've gone through the other calls of `X509V3_EXT_d2i` and it seems to me that the result is always checked. There is just one case where the check is not immediate and that I'll analyze again. Do you have a specific case to mention?

**Comment by abh3** [comment]
No specific case other than for some strange reason we got a cert with a 
bad extension. It was the first time I've seen that crash and now it will 
be the last one, thanks :-)

Andy

**Comment by wyang007** [comment]
I suppose that this fix hasn't reached to EPEL and I need to compile from the source?

**Comment by abh3** [comment]
Likely so, there is a usual deley here.
