### ISSUE TITLE
CRYPTO_malloc_init is called multiple times

### ISSUE THREAD

**Issue by abh3** [italiangrid/voms#96]
CRYPTO_malloc_init() should be a one time call but, unfortunately, it is called every time vomsdata::check_cert() is called (see api_util.cc:740). Why is one-time initialization performed more than once? While this might not be a practical problem for single threaded programs it may cause undefined behavior in a MT environment. Indeed, we just saw a crash involving vomsdata::check_cert() and while this may not be the issue; multiple one-time initializations certainly do make it a suspect.

**Comment by abh3** [comment]
According to the OpenSSL FAQ sheet "it is as important to add CRYPTO_malloc_init() prior first call to OpenSSL. So, I would suggest calling this in the general OpenSSL initialization phase.  In the current code, it is obviously not the case here.

**Comment by giacomini** [comment]
That call has already been removed as part of the work to support OpenSSL-1.1. See https://github.com/italiangrid/voms/blob/9dda67250e7ccfe94abb0ce113a23beda96e5409/src/api/ccapi/api_util.cc#L745 (from the `develop` branch). The change will be included in the next release.
